# Generated by Django 5.1.6 on 2025-02-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spikedata',
            old_name='modified_value',
            new_name='spike_value',
        ),
    ]
